pagopa/pagopa-ecommerce-event-dispatcher-service

helm/values-dev.yaml, helm/values-uat.yaml, src/main/kotlin/it/pagopa/ecommerce/scheduler/config/QueuesConsumerConfig.kt, src/main/resources/application.properties
=> Fix queues  configs

pom.xml
* fix openapi link for transactions-service spec
=> fix(build): fix openapi link for transactions-service spec

pom.xml
Added skipCheckoutIfExists tag into pom.xml for SCM plugin
Added skipCheckoutIfExists tag into pom.xml for SCM plugin for skip the commons dependency compilation if the artifact is available into local repository
Tested by pipeline build.
=> Added <skipCheckoutIfExists> tag for SCM plugin

helm/values-uat.yaml
=> feat: set affinity for uat env

pom.xml, src/main/kotlin/it/pagopa/ecommerce/scheduler/queues/TransactionActivatedEventsConsumer.kt, src/main/kotlin/it/pagopa/ecommerce/scheduler/queues/TransactionClosureErrorEventConsumer.kt, src/main/kotlin/it/pagopa/ecommerce/scheduler/repositories/TransactionsViewRepository.java, src/main/kotlin/it/pagopa/ecommerce/scheduler/services/NodeService.kt, src/test/kotlin/it/pagopa/ecommerce/scheduler/queues/TransactionActivatedEventsConsumerTests.kt, src/test/kotlin/it/pagopa/ecommerce/scheduler/queues/TransactionClosureErrorEventConsumerTests.kt, src/test/kotlin/it/pagopa/ecommerce/scheduler/services/NodeServiceTests.kt
* update `pagopa-ecommerce-commons` version to v0.4.2
Local unit tests
Depends on pagopa/pagopa-ecommerce-commons#22
=> refactor: update `pagopa-ecommerce-commons` version to v0.5.0

helm/values-dev.yaml
Increased helm dev values
Increased value of memory for the pod from **384 mi** to **512 mi** and initialDelaySecond from 60 to 80 into DEV environment.
=> Feat: changed memory and initialDelaySeconds into helm dev

pom.xml, src/main/kotlin/it/pagopa/ecommerce/scheduler/exceptions/BadTransactionStatusException.kt, src/main/kotlin/it/pagopa/ecommerce/scheduler/exceptions/TransactionEventNotFoundException.kt, src/main/kotlin/it/pagopa/ecommerce/scheduler/exceptions/TransactionNotFound.kt, src/main/kotlin/it/pagopa/ecommerce/scheduler/queues/TransactionActivatedEventsConsumer.kt, src/main/kotlin/it/pagopa/ecommerce/scheduler/queues/TransactionClosureErrorEventConsumer.kt, src/main/kotlin/it/pagopa/ecommerce/scheduler/repositories/TransactionsEventStoreRepository.kt, src/main/kotlin/it/pagopa/ecommerce/scheduler/repositories/TransactionsViewRepository.java, src/main/kotlin/it/pagopa/ecommerce/scheduler/services/NodeService.kt, src/test/kotlin/it/pagopa/ecommerce/scheduler/queues/TransactionActivatedEventsConsumerTests.kt, src/test/kotlin/it/pagopa/ecommerce/scheduler/queues/TransactionClosureErrorEventConsumerTests.kt, src/test/kotlin/it/pagopa/ecommerce/scheduler/services/NodeServiceTests.kt, src/test/kotlin/it/pagopa/ecommerce/scheduler/utils/TestUtil.kt
Depends on pagopa/pagopa-ecommerce-commons#42
=> [CHK-1104] refactor: update `pagopa-ecommerce-commons` to v0.6.1

pom.xml, src/main/kotlin/it/pagopa/ecommerce/scheduler/queues/TransactionActivatedEventsConsumer.kt, src/test/kotlin/it/pagopa/ecommerce/scheduler/queues/TransactionActivatedEventsConsumerTests.kt
* update `pagopa-ecommerce-commons` to v0.7.1
Depends on #30
=> feat(commons): update `pagopa-ecommerce-commons` to v0.7.1

src/main/kotlin/it/pagopa/ecommerce/scheduler/queues/TransactionActivatedEventsConsumer.kt, src/main/kotlin/it/pagopa/ecommerce/scheduler/queues/common.kt, src/test/kotlin/it/pagopa/ecommerce/scheduler/queues/TransactionActivatedEventsConsumerTests.kt
Add logic for transaction transition from ACTIVATED to EXPIRED_NOT_AUTHORIZED for those transactions for those transactions that has expired and no authorization was requested at all
Handling of transition from ACTIVATED to EXPIRED_NOT_AUTHORIZED state for transaction that expire after been activated
Local junit test + local test using ecommerce local
=> CHK-1230-expired-not-authorized

.devops/azure-templates/chart-current-version.yml, .devops/azure-templates/helm-microservice-chart-deploy.yml, .devops/deploy-pipelines.yml
Make blue/green deployment optional 
Make blue/green deployment optional
=> fix: optional blue deployment

pom.xml
* update eCommerce-commons version to v0.8.7
=> feat(commons): update ecommerce-commons version to v0.8.7

helm/values-dev.yaml, helm/values-uat.yaml
Fix helm values
Fix helm values
=> fix: helm values

src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/config/QueuesConsumerConfig.kt
Increase events processed per seconds
Increase events processed per seconds
=> fix: increase event per second

pom.xml, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/common.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/eventretry/RetryEventService.kt
Update commons version to fit new model containing transfer list in transaction and payment info
update pom
update payment info refes
Since activatev2 contains new info, data model need to be updated
Tests were performed in dev env
=> CHK-1362-update-commons-version

pom.xml, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/UserReceiptMailBuilder.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/UserReceiptMailBuilderTest.kt
Added RRN handling in the template of the success email.
RRN handling has been added in the template of the success email, retrieved from the authorization completion event.
The tests were performed locally.
=> CHK-1438-rrn-into-template

src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/NodeService.kt
Additional payment info missed totalAmount
Fix logo uri path
=> [CHK-1502] Additional Payment Info Fix

pom.xml
Upgrade commons library version to latest
Upgrade commons library version to latest
Junit test + local test
=> feat: upgrade commons version to latest

src/main/resources/application.properties
Change mongo readPreference to `primaryPreferred`
With this mode all read operations will be redirect to primary partition if available with fallback on secondary ones.
The `maxStalenessSeconds` parameter is set to it's the minimum value of 90 seconds in order to block reads from a replica older that 90 seconds
See https://learn.microsoft.com/en-us/azure/cosmos-db/mongodb/readpreference-global-distribution#read-using-read-preference-mode
Those modifications are needed in order to redirect all read operations to the primary replica and lower the required consistency level
=> feat: specify read preference mode

src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/NodeService.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/NodeServiceTests.kt
Fix additional payment informations fields format:
1. Amounts as strings (example 1€ formatted as 1.00)
2. TimestampOperation formatted as yyyy-MM-ddThh:mm:ss
3. Removed `tipoVersamento` field
4. Fees were directly converted from integer to BigDecimal instead of converting it from int to eurocent first
Those modifications are needed in order to make additionalPaymentInformations compliant with the Nodo expected body
Junit tests
=> fix: close payment additionalData

helm/values-dev.yaml, helm/values-uat.yaml
=> fix: update pgs url

src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/config/WebClientConfig.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/config/WebClientConfigTest.kt
- Remove null-value json properties in node requests
- Add `JsonInclude.Include.NON_NULL` rule to jackson mapper to avoid adding null-value json properties
- Align to Nodo web-services requirements
=> [CHK-1510] fix: drop null-value in body serialization

src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/client/PaymentGatewayClient.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/common.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionsRefundEventsConsumerTests.kt
1. Add handling for PGS DENIED status so refund process will be blocked and no more attempts will be performed if DENIED response is received
2. Refunding process logs refactoring to make more verbose about the invoked PGS and status response received
Those modifications are needed in order to handle DENIED PGS response and block refund retries
Junit test + local test using ecommerce local
=> Chk 1521 stop refund retry on denied response

helm/values-prod.yaml
=> feat(helm): CHK-1539 Add helm value for prod

.devops/deploy-pipelines.yml
Add kubectl installer for deploy pipelines
Add kubectl installer for deploy pipelines
=> fix: add kubectl installer for UAT deploy pipelines

src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/common.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionExpirationQueueConsumerTests.kt
Modify logic to perform refund disabling refund in case transaction got stuck in CLOSED status and close payment response outcome is OK.
Those modifications are needed in order to avoid refund when sendPaymentResult is not received
Junit tests
=> fix: refund logic

pom.xml
=> feat(common): increase common version

pom.xml, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/client/NodeClient.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/client/NodeClientTest.kt
Added into closePayment request new query param ecomm.
The change was made to add a new query param to the close payment request to the node.
=> feat: added clientId query param into close payment request

pom.xml
=> [CHK-1636] update common version

src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionExpirationQueueConsumer.kt
Add transaction id into event dispacher logs for close payment skip logic
Add transaction id into event dispacher logs for close payment skip logic
=> fix: add transaction id into logs

pom.xml, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/common.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/UserReceiptMailBuilder.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionNotificationsQueueConsumerTest.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/UserReceiptMailBuilderTest.kt
Update commons version to 0.18.2
Update commons version to 0.18.2
=> feat: update commons version

helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, pom.xml, src/main/resources/logback-spring.xml
- Add logback ECS encoder to format log in json ECS format
- Disable APM agent log sending since logs will be ingested by filebeat agent
Those modifications are needed in order to properly format log in json ECS format
Local run
`{"@timestamp":"2023-06-21T08:20:30.256Z","log.level": "INFO","message":"Started EventDispatcherApplicationKt in 2.59 seconds (JVM running for 2.916)","ecs.version": "1.2.0","service.name":"pagopa-ecommerce-event-dispatcher-service","service.version":"0.6.3","event.dataset":"pagopa-ecommerce-event-dispatcher-service","process.thread.name":"main","log.logger":"it.pagopa.ecommerce.eventdispatcher.EventDispatcherApplicationKt"}`
=> feat(logging): format log in ECS json format

Dockerfile, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml
* use OpenTelemetry monitoring agent instead of Elastic APM
=> [CHK-1566] feat(monitoring): use OpenTelemetry monitoring agent instead of Elastic APM

.devops/deploy-pipelines.yml, .github/actions/check-pr-semver-labels/action.yml, .github/workflows/check_pr.yml, .github/workflows/deploy.yml, README.md
Add github action that check for the presence of well-formed tags that will be used to trigger semantic versioning parameters for deploy module once PR is merge on main branch.
Those tags are:
| Tag                | Semantic versioning scope | Meaning                                                           |
|--------------------|---------------------------|-------------------------------------------------------------------|
| patch              | Application version       | Patch-bump application version into pom.xml and Chart app version |
| minor              | Application version       | Minor-bump application version into pom.xml and Chart app version |
| major              | Application version       | Major-bump application version into pom.xml and Chart app version |
| …
=> feat(CD): deploy on pr merge

src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/NodeService.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/NodeServiceTests.kt
Fixed fields for closePayment KO after authorization from PGS KO
The change was made to align the fields of the KO payment closure in case of KO authorization from the PGS
The tests was performed locally
=> fix(close-payment fields) - fixed close payment ko fields

src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionNotificationsQueueConsumer.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionNotificationsQueueConsumerTest.kt
=> [CHK-1565] feat(tracing): add tracing to `TransactionNotificationsQueueConsumer`

src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionNotificationsQueueConsumer.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionNotificationsQueueConsumerTest.kt
Reverts pagopa/pagopa-ecommerce-event-dispatcher-service#119
=> Revert "[CHK-1565] feat(tracing): add tracing to `TransactionNotificationsQueueConsumer`"

pom.xml, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/config/OpenTelemetryConfig.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionExpirationQueueConsumer.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionsRefundQueueConsumer.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/common.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/eventretry/TracedRetryEventService.kt, src/main/resources/META-INF/services/com.azure.core.util.serializer.JsonSerializerProvider, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionClosePaymentQueueConsumerTests.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionClosePaymentRetryQueueConsumerTests.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionExpirationQueueConsumerTests.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionNotificationsQueueConsumerTest.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionsRefundEventsConsumerTests.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/eventretry/ClosureRetryServiceTests.kt, src/test/resources/META-INF/services/com.azure.core.util.serializer.JsonSerializerProvider
**NOTE:** Was #108, mistakenly closed
* correlate event dispatcher async processing with original endpoint
Depends on https://github.com/pagopa/pagopa-ecommerce-commons/pull/94
Depends on #107
=> [CHK-1565] feat(monitoring): correlate event dispatcher async processing with original endpoint

src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionsRefundQueueConsumer.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionsRefundEventsConsumerTests.kt
=> [CHK-1565] feat(tracing): add tracing support to `TransactionRefundQueueConsumer`

src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionRefundRetryQueueConsumer.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionRefundRetryQueueConsumerTest.kt
=> [CHK-1565] feat(tracing): add tracing to `TransactionRefundRetryQueueConsumer`

src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionClosePaymentQueueConsumer.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionClosePaymentQueueConsumerTests.kt
* add tracing to `TransactionClosePaymentQueueConsumer`
This PR adds tracing context propagation to the consumer side of `CLOSURE_EVENT` events.
This allows the monitoring system to correlate events to the producer side.
=> [CHK-1565] feat(tracing): add tracing to `TransactionClosePaymentQueueConsumer`

src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionClosePaymentRetryQueueConsumer.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionClosePaymentRetryQueueConsumerTests.kt
=> [CHK-1565] feat(tracing): add tracing to transaction closePayment retry consumer

src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionClosePaymentQueueConsumer.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionClosePaymentQueueConsumerTests.kt
* allow closePayment consumer to parse legacy untraced events
This PR allows a smoother deployment transition by allowing the service to parse both new events (with embedded tracing information) and old events (without tracing information)
=> fix(events): allow closePayment consumer to parse legacy untraced events

src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionNotificationsQueueConsumer.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionNotificationsQueueConsumerTest.kt
* allow notification consumer to parse legacy untraced events
This PR allows a smoother deployment transition by allowing the service to parse both new events (with embedded tracing information) and old events (without tracing information)
=> fix(events): allow notification consumer to parse legacy untraced events

src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionNotificationsRetryQueueConsumer.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionNotificationsRetryQueueConsumerTest.kt
* allow notification retry consumer to parse legacy untraced events
This PR allows a smoother deployment transition by allowing the service to parse both new events (with embedded tracing information) and old events (without tracing information)
=> [CHK-1766] fix(events): allow notification retry consumer to parse legacy untraced events

helm/values-prod.yaml
* fix autoscaling configuration for service in prod
This PR fixes autoscaling parameters for PROD environment.
=> fix(helm): fix autoscaling setup for prod env

helm/values-prod.yaml
=> fix(enable-log-sending) - enabled log sending

pom.xml, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/config/QueuesConsumerConfig.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/exceptions/InvalidEventException.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionExpirationQueueConsumer.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionClosePaymentQueueConsumer.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionClosePaymentRetryQueueConsumer.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionNotificationsQueueConsumer.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionNotificationsRetryQueueConsumer.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionRefundRetryQueueConsumer.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionsRefundQueueConsumer.kt
Fix event deserialization for different versions
Fix event deserialization for different versions
=> Chk 1921 v2 event deserialization

src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/exceptions/InvalidEventException.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionClosePaymentQueueConsumer.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionClosePaymentRetryQueueConsumer.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionExpirationQueueConsumer.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionNotificationsQueueConsumer.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionNotificationsRetryQueueConsumer.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionRefundRetryQueueConsumer.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionsRefundQueueConsumer.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/common.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionClosePaymentQueueConsumerTests.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionClosePaymentRetryQueueConsumerTests.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionExpirationQueueConsumerTests.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionNotificationsQueueConsumerTest.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionNotificationsRetryQueueConsumerTest.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionRefundRetryQueueConsumerTest.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionsRefundEventsConsumerTests.kt
Fix event parsing error: in case of event parsing error event has to be written into dead-letter queue
Those modification are needed in order to properly handle parsing error of input events
Junit tests + test with eCommerce local
=> fix(event parsing): invalid event written to dead-letter queue

src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionClosePaymentQueueConsumerTests.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionClosePaymentQueueConsumerTests.kt
Add timeout for assertions that tests logic executed in doFinally method.
[doFinally](https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Mono.html#doFinally-java.util.function.Consumer-) method is executed after Mono completion this cause tests random failure caused by assertion execution check is not always executed after doFinally method have been executed.
Junit tests
=> Fix test assertions

pom.xml, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeService.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/v2/UserReceiptMailBuilder.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionClosePaymentQueueConsumerTests.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionClosePaymentQueueConsumerTests.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeServiceTests.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/v2/UserReceiptMailBuilderTest.kt
Modified login for retrieve logo and card brand for handle NPG logic
The change was made to handle the modification of the v2 event body to recover the paper brand and logo
=> CHK-1974: feat logo mail npg

pom.xml, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionClosePaymentQueueConsumerTests.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionClosePaymentQueueConsumerTests.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeServiceTests.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/v2/UserReceiptMailBuilderTest.kt
* update `pagopa-ecommerce-commons` version to 0.26.0
Ordinary maintenance
=> chore(deps): [CHK-2004] - update `commons` version to 0.26.0

src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/client/NodeClient.kt
Add Nodo closePayment response outcome and error code, if any
This logs are useful for analyze Nodo interactions
Junit tests checking that outcome and error are properly logged
=> fix: add logging for nodo outcome and error code

helm/values-prod.yaml
- set minReplica to 3 for prod env, one for availability zone;
- add antiPodAffinity with[ topology.kubernetes.io/zone](https://kubernetes.io/docs/reference/labels-annotations-taints/#topologykubernetesiozone);
The goal of this PR is to increase the availability  by deploying at least one pod per availability zone.
=> feat: CHK-275 add antiPodAffinity

src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionClosePaymentQueueConsumer.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionClosePaymentRetryQueueConsumer.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionExpirationQueueConsumer.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionNotificationsQueueConsumer.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionNotificationsRetryQueueConsumer.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionRefundRetryQueueConsumer.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionsRefundQueueConsumer.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/common.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionClosePaymentQueueConsumerTests.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionClosePaymentRetryQueueConsumerTests.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionExpirationQueueConsumerTests.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionNotificationsQueueConsumerTest.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionNotificationsRetryQueueConsumerTest.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionRefundRetryQueueConsumerTest.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionsRefundEventsConsumerTests.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionRefundRetryQueueConsumerTest.kt
Depends on #176 
Add dead letter event tracing also for v1 queue consumers
Add dead letter event tracing also for v1 queue consumers
Junit tests + test with eCommerce local
=> feat: [CHK-2083] Dead letter dashboard v1 events

helm/values-prod.yaml
FIx autoscaling `enable` key for prod
FIx autoscaling `enable` key for prod
=> fix: helm values prod

src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v1/NodeService.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeService.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v1/NodeServiceTests.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeServiceTests.kt
Set date time zone to `Europe/Paris` before formatting it to local date time
Set date time zone to `Europe/Paris` before formatting it to local date time
Local tests
=> fix: [CHK-2221] - add junit tests

helm/values-prod.yaml
=> feat: CHK-1987 disable apm log send

src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionClosePaymentRetryQueueConsumer.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/common.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeService.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/ExceptionHandlerTest.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/config/redis/EventDispatcherCommandsTemplateWrapperTest.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/config/redis/EventDispatcherReceiverStatusTemplateWrapperTest.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/controller/EventReceiversApiControllerTest.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/redis/streams/RedisStreamConsumerTest.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/EventReceiverStatusPollerTest.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/EventReceiversServiceTest.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/InboundChannelAdapterHandlerServiceTest.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeServiceTests.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/stream/RedisStreamMessageSourceTest.kt
Depends on #200 
Add junit tests to cover all new code branches
Add redirect event temporary handling (TODO() methods) in order to compile module after eCommerce commons library version upgrade
Those modifications are needed in order to properly test all code branches
Junit tests
=> [CHK-2388] - part5  feat: add junit tests

src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/controller/EventReceiversApiController.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/exceptionhandler/ExceptionHandler.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/exceptions/NoEventReceiverStatusFound.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionClosePaymentRetryQueueConsumer.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/common.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeService.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/validation/BeanValidationConfiguration.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/validation/CustomLocalValidatorFactoryBean.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/validation/SuspendAwareKotlinParameterNameDiscoverer.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/ExceptionHandlerTest.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/config/redis/EventDispatcherCommandsTemplateWrapperTest.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/config/redis/EventDispatcherReceiverStatusTemplateWrapperTest.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/controller/EventReceiversApiControllerTest.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/redis/streams/RedisStreamConsumerTest.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/EventReceiverStatusPollerTest.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/EventReceiversServiceTest.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/InboundChannelAdapterHandlerServiceTest.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeServiceTests.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/stream/RedisStreamMessageSourceTest.kt
Add rest controller implementation that, using previously implemented services actualize received commands and perform event receiver statuses query
Those modifications are needed in order to allow api utilization
Junit tests + local tests with eCommerce local + test in DEV environment
=> [CHK-2388] - part 4 feat: add rest api command controller and request validation

src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v1/NodeService.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeService.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v1/NodeServiceTests.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeServiceTests.kt
Set value for `fee`, `amount` and `totalAmount` in eurocents for transaction details section in close payment requests.
=> [CHK-2277] feat(close payment): eurocents in transaction details

helm/values-prod.yaml
Add rolling update deployment strategy configured as:
- `maxSurge` -> 100%
- `maxUnavailable` -> 100%
With this configuration all existent pods will be destroyed and will be started deployment for new pods as soon as deploy phase start
This deployment strategy will make deployment phase faster for event dispatcher, replacing all active pods with new ones, avoiding old pod version deploy during deployment phase.
This deployment strategy is supported by the `event receivers` shutdown feature so that, during a new event dispatcher version deployment the following steps will be executed:
1. turn down all event receivers
2. replace all at once all deployed pods with the new version
3. restart event receivers once deployment phase have been completed
This way the events receiving interruption …
=> fix(chart): [CHK-2437] - add deployment strategy for event dispatcher

helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, pom.xml, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/client/NodeClient.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/exceptions/BadClosePaymentRequest.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/exceptions/ClosePaymentErrorResponseException.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionClosePaymentQueueConsumer.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionClosePaymentRetryQueueConsumer.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionExpirationQueueConsumer.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/common.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionExpirationQueueConsumer.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/common.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/ClosePaymentHelper.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v1/NodeService.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/client/NodeClientTest.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/CommonTests.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionClosePaymentQueueConsumerTests.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionClosePaymentRetryQueueConsumerTests.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionExpirationQueueConsumerTests.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/CommonTests.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionExpirationQueueConsumerTests.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/ClosePaymentHelperTests.kt
There have been applied modifications to hotfix the refund handling in case of error handling Close payment vs Node.
In particular the following modifications have been applied:
1. increase Node connection and read timeout to 14000 milliseconds from 10000
2. add logic to properly handle Node close payment responses:
a. wrap all exceptions to `ClosePaymentErrorResponseException`. This exception wraps all errors retrieving, if available, Node error response (field description in error response)
b. during retry this exception is checked and actions are performed based on the result received (1)
3. exclude transaction in state CLOSURE_ERROR from refundable ones. If a transaction is stuck in this state is send to dead letter events with MANUAL_CHECK_REQUIRED status in order to avoid refunding …
=> fix(refund): handle refund logic for close payment KO responses

pom.xml, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/client/NodeClient.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/config/WebClientConfig.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/client/NodeClientTest.kt
Fix code to extract Node close payment error response code
Fix code to extract Node close payment error response code
Junit tests
=> fix: extract node close payment error response

helm/values-uat.yaml
Make UAT blue env point to dedicated queues
Make UAT blue env point to dedicated queues
=> chore(conf): change uat blue env to point dedicated queues

command-postman-collection/commands.postman_collection.json
Update commands collection base path
Make postman command collection point to prod ingress
=> chore(command collection): update base path

Dockerfile, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, pom.xml
- update opentelemetry agent to v2.1.0
=> chore(open-telemetry-agent): [CHK-2534] - update agent version

src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeService.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeServiceTests.kt
* fix `additionalPaymentInformations.{fee,totalAmount}` types
=> fix(closepayment): fix `additionalPaymentInformations.{fee,totalAmount}` types

pom.xml, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeService.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeServiceTests.kt
* update commons
Depends on pagopa/pagopa-ecommerce-commons/pull/184
=> [CHK-2575] refactor(redirect): update commons

src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/ClosePaymentHelper.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/ClosePaymentHelperTests.kt
Update transaction status and write closure error event for error received from Nodo performing ClosePayment.
Before this fix, in case of an error for which no retry has to be performed the transaction got stuck in CLOSURE_REQUESTED status
This fix is required in order to properly update transaction status in case of unretriable error performing close payment 
Junit tests
=> fix(v2): CLOSURE_ERROR status update for ClosePayment error

src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/RefundService.kt
Add logging for refund operation and errors during communication with NPG
Those modifications make clearer tracking NPG refund operation and received errors
Junit tests
=> fix(NPG-refund): add logging for refund operation and errors

helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml
The goal of this PR is to also add the Redis hostname as a secret, allowing the synchronization of the reference to the new Redis password with any potential hostname updates.
=> refactor(redis): use new redis refs

pom.xml
Fix ecommerce commons branch ref
Fix ecommerce commons branch ref
=> fix: ecommerce commons ref

pom.xml, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeService.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeServiceTests.kt
Depends on https://github.com/pagopa/pagopa-infra/pull/2014
Fix MyBank close payment request field `mybankTransactionId`: renamed to `myBankTransactionId`
Modification needed in order to make close payment request compliant to SANP specifications
Local project build
=> fix: update myBankTransactionId field case

src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/client/PaymentGatewayClient.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/config/QueuesProducerConfig.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/config/WebClientConfig.kt
Configure Netty DNS resolver to use 1 as number of dots in name resolution
This modification is a porting of the fix performed [here](https://github.com/pagopa/pagopa-ecommerce-payment-methods-service/pull/191) and applied to all clients
Test in UAT env (during performance tests)
=> Chk 2785 implementation tuning

pom.xml
Depends on https://github.com/pagopa/pagopa-ecommerce-commons/pull/201
=> fix: [CHK-2880] Using common with no parent tracing fix

pom.xml
=> fix: Revert ecommerce-common no parent tracing

.devops/deploy-pipelines.yml
* don't fail the pipeline if the beta deployment does not exist
=> fix: don't fail the pipeline if the beta deployment does not exist

helm/values-prod.yaml
=> update psp list

pom.xml
Depends on https://github.com/pagopa/pagopa-ecommerce-commons/pull/208
Update eCommerce commons version with fix for NpgClient.getOrders api call that add a trailing slash to path
This modification is needed in order to make GET orders URLs with a dot (`.`) in the value correctly interpretated by NPG backend
Local test with eCommerce local and NPG mock
`Before modification` (GET order without trailing slash)
`After modification` (GET order with trailing slash
=> fix(npg-client): add trailing slash to GET orders

helm/values-prod.yaml
Add psp api keys for Redirect
Add psp api keys for Redirect
=> chore(conf): add redirect psp api keys

helm/values-dev.yaml, helm/values-uat.yaml
=> feat(pspList): add pspId IFSPIT21 to pspIdList

helm/values-prod.yaml
-  set min replica to 5 in prod
=> chore: increase min replicas

pom.xml, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/client/NodeClient.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeService.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/PaymentCode.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/v2/UserReceiptMailBuilder.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/v2/UserReceiptMailBuilderTest.kt
Depends on https://github.com/pagopa/pagopa-infra/pull/2256
Update reference to close payment definitions. Update request body building for both payment method.
Close payment request for
- Applepay
- Satispay
Add applepay and satispay payment method
=> [CHK-3016] feat(applepay + satispay) : update close payment request body

helm/values-prod.yaml
* enable PSP iConto for cards payments in prod
=> [CHK-3034] feat: enable PSP iConto for cards payments in prod

helm/values-prod.yaml
Increase PROD memory
Increase PROD memory
=> fix: increase PROD memory

src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/common.kt
=> add wisp redirect client in refund chain

.devops/deploy-pipelines.yml
fix manual check dependencies
fix manual check dependencies
=> fix: pipeline dependencies

.devops/deploy-pipelines.yml
fix checkout release version variable interpolation
fix checkout release version variable interpolation
=> fix: pipeline checkout release version

src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/client/NodeClient.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/exceptions/ClosePaymentErrorResponseException.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionClosePaymentRetryQueueConsumer.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/ClosePaymentHelper.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionClosePaymentRetryQueueConsumerTests.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/ClosePaymentHelperTests.kt
Added a refund transaction case.
This service will refund a transaction in case closePayment returns a response with http 400 status and "Unacceptable outcome when token has expired" error description
=> [CHK-3215] feat(refund): add refund transaction case

helm/values-prod.yaml
Enable last usage FF for prod env
Enable last usage FF for prod env
=> chore(last usage): [CHK-3314] enable ff for prod env

helm/values-prod.yaml
1. Decrease probes `initialDelaySeconds` since POD starts earlier since CPU limit increase
2. change rollout strategy to maxSurge 2 and maxUnavailable 0
1. Since CPU limit increase POD starts up faster so initial delay seconds can be lowered according to new startup time
2. previously rollout strategy was a complete pod substitution to reduce the amount of time needed for rolling out new pods: this stategy have a drow back in case of new release misconfiguration where pod cannot be started successfully and will cause all pods to be down.
This will not be always a problem during normal deployments with staging/prod strategy: during new pod deployments staging ones (clone of the prod configuration before deployment) are up and running.
In case of rolling update triggered by configuration …
=> feat: deployment tuning

helm/values-prod.yaml
Restore maxSurge and maxUnavailable to 100%
This modification is needed because during staging/prod deployment this strategy will create too many pods and cause deploy to remain in pending state due to missing resources in the cluster
=> fix: restore max surge and max unavailable to 100%

pom.xml, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/common.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/EndToEndId.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/AuthorizationRequestedHelperTests.kt
- Use the utils class to retrieve the paymentEndToEndId from the npg getOrder call
The change is needed since the business that retrieves the field was put on ecommerce-commons
Junit Test
=> [PPABV-62] Edit get payment end to end

.devops/code-review-pipelines.yml
- added integration test on the code review pipeline through local Azure agent using the docker-compose configuration
To properly test that the dispatcher workflow ends with a valid and correct transaction status
=> [PPABV-64] feat: add CR integration test through local agent and docker compose config

pom.xml, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeService.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeServiceTests.kt
depends on https://github.com/pagopa/pagopa-infra/pull/2705
Added authorizationRequestId to additionalPaymentInformations for apple pay closePayment (v2)
We need to comply with a new requirement
=> feat: [CHK-3626] Adding authorizationRequestId to additionalPaymentInformations for apple pay closePayment (v2)

.devops/code-review-pipelines.yml, README.md
Depends on https://github.com/pagopa/pagopa-ecommerce-local/pull/182 https://github.com/pagopa/pagopa-ecommerce-local/pull/181
- add events integration test from ecommerce-local api tests into code-review pipeline
The goal of this PR is to verify that all the queue's events handled by the service obtains the correct transaction status transiction.
Pipeline code-review
=> [CHK-3648] feat: add events integration tests into code review

.devops/azure-templates/chart-github-release.yml, .devops/code-review-pipelines.yml
- updated versions for pipeline tasks which generated deprecation warnings on remote build and deploy processes
This update was needed to prevent future execution failures on code review and deploy pipelines
- Pipeline jobs executed successfully and without deprecation warnings
=> [PIDM-41] chore(azdo-pipeline-tasks): update tasks versions

.github/workflows/semver_release.yaml
Add missing pom version bump
Add missing pom version bump
=> fix(semver): pom version bump

.github/actions/check-pr-semver-labels/action.yml
trigger deployment pipeline to test version bump and release creation
trigger deployment pipeline to test version bump and release creation
=> chore: trigger pipeline

.github/workflows/semver_release.yaml
Version bump have to be skipped in case of skip release label
Version bump have to be skipped in case of skip release label
=> fix: add condition to skip release

.github/workflows/check_pr.yml
=> Chk 4095 fix deploy pipeline

.github/workflows/semver_release.yaml
Fix version bump
Fix version bump
=> fix: version bump script

.devops/code-review-pipelines.yml, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/config/WebClientConfig.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/client/NodeClientTest.kt
This reverts commit 8700a64744130dd54b303ad50c8876f6b584336e.
- Added api key as default header for the closePayment request
- Updated env vars
- Updated helms
- Updated resources
- Updated tests
=> [CHK-4003] feat(nodo): add api key in closePayment

pom.xml, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeService.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/PaymentCode.kt, src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/v2/UserReceiptMailBuilder.kt, src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeServiceTests.kt
Depends on https://github.com/pagopa/pagopa-infra/pull/3222
Add google pay method close payment request body building method
=> [PIDM-753] google pay close payment missing

.devops/code-review-pipelines.yml, .devops/deploy-pipelines.yml
Add pending status tests for both CR and deployment pipelines, publishing results after test execution.
Those tests perform checks against the expected transaction status transition and the dead letter queue event writing once a transaction get stuck in a pending status.
Tests in CR pipeline are made using mocks to simulate the downstream dependencies ko's
For deployment pipeline a subset of the code review tests are executed (the one that expect a 404 from a downstream dependencies for example) since they are performed against the real DEV/UAT downstream dependencies where there is no way to drive a specific KO
Integration test integration and execution in [CR](https://dev.azure.com/pagopaspa/pagoPA-projects/_build/results?buildId=223419&view=results) and [deployment pipeline …
=> feat: integrate pending status tests in pipelines
