pagopa/pagopa-ecommerce-event-dispatcher-service

src/main/kotlin/it/pagopa/ecommerce/scheduler/queues/TransactionActivatedEventsConsumer.kt
src/test/kotlin/it/pagopa/ecommerce/scheduler/queues/TransactionActivatedEventsConsumerTests.kt
src/test/kotlin/it/pagopa/ecommerce/scheduler/queues/TransactionClosureErrorEventConsumerTests.kt

* make `TransactionActivatedEventsConsumer` handle refund retry events
This PR allows `pagopa-ecommerce-scheduler-service` to handle refund retry events generated by the pending transactions batch (for this PR in particular we now handle `TransactionRefundRetriedEvent` as defined in pagopa/pagopa-ecommerce-commons#23).
Local unit tests
Depends on #24

[CHK-1026] feat(consumers): add event consumer for transaction retry refund event

---

src/main/kotlin/it/pagopa/ecommerce/scheduler/queues/TransactionClosureErrorEventConsumer.kt
src/test/kotlin/it/pagopa/ecommerce/scheduler/queues/TransactionClosureErrorEventConsumerTests.kt

* add event consumer for transaction retry closure event
This PR allows pagopa-ecommerce-scheduler-service to handle refund retry events generated by the pending transactions batch (for this PR in particular we now handle TransactionRefundRetriedEvent as defined in https://github.com/pagopa/pagopa-ecommerce-commons/pull/23).
Local unit tests
Depends on #24

[CHK-1026] feat(consumers): add event consumer for transaction retry closure event

---

pom.xml
src/main/kotlin/it/pagopa/ecommerce/scheduler/queues/TransactionActivatedEventsConsumer.kt
src/main/kotlin/it/pagopa/ecommerce/scheduler/queues/TransactionExpiredEventsConsumer.kt
src/main/kotlin/it/pagopa/ecommerce/scheduler/queues/common.kt
src/test/kotlin/it/pagopa/ecommerce/scheduler/queues/TransactionActivatedEventsConsumerTests.kt
src/test/kotlin/it/pagopa/ecommerce/scheduler/queues/TransactionExpiredEventsConsumerTests.kt

This PR is the starting base for the PR #34 that adds the refund retry logic
Change refund logic to write ahead refund requested event to event store (and update view to REFUND_REQUESTED) and then write one of REFUNDED or REFUND_ERROR events based on the PGS refund request outcome
Those modifications are needed in order to reflects the new ecommerce transactions state machine statuses
Junit tests

fix: refund process events

---

pom.xml
src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionExpirationQueueConsumer.kt
src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/common.kt
src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionExpirationQueueConsumerTests.kt
src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionRefundRetryQueueConsumerTest.kt
src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/TestUtil.kt

1. Fix bug CHK-1359: REFUND_REQUESTED and REFUND_ERROR were wrongly marked as transient statuses and then transaction in those statuses got wrongly processed by expiration queue that mark those as EXPIRED and then process refund again --> resolved upgrading commons version
2. Fix bug CHK-1360: refund pipeline write REFUND_ERROR event every time a refund error happen, also if this was triggered by a retry event
3. Add junit tests to cover above bug fixes
1. This fix resolve refund for a transaction to be processed twice
2. This fix resolve the fact that refund error event is written every time an error happens during refund retry: now refund error event is written only once at the first error 
Junit tests

[CHK-1359,CHK-1360] fix refund error event written multiple times

---

src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/NodeService.kt
src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/NodeServiceTests.kt

Fix ClosePaymentRequest additionalInformations.timestampOperation date format to be formatted in `yyyy-MM-ddThh:mm:ss` format
Those modifications are needed to format `timestampOperation` closePayment field correctly
Junit tests

fix: ClosePayment additionalInformations.timestampOperation format

---

pom.xml
src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/UserReceiptMailBuilder.kt
src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/TestUtil.kt
src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/UserReceiptMailBuilderTest.kt

Depends on https://github.com/pagopa/pagopa-ecommerce-transactions-service/pull/204
Change logo uri origin. Now logo uri is taken from authorization requested data instead of user receipt data
Change logo uri origin. Now logo uri is taken from authorization requested data instead of user receipt data
Junit tests

fix: change logo uri origin

---

src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionExpirationQueueConsumer.kt
src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/common.kt
src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionExpirationQueueConsumerTests.kt

Add handling for `CANCELLATION_EXPIRED` expiration status.
Into this status a transaction can come for a transaction expired in CANCELLATION_REQUESTED status or from expiration into CLOSURE_ERROR status for a transaction canceled by user
Those modifications are needed in order to update expiration status accordingly to the fact that transaction was cancelled by user or not
Junit test and local tests with ecommerce local

fix: expiration on closure error from user cancel

---

src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionExpirationQueueConsumer.kt
src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/common.kt
src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionExpirationQueueConsumerTests.kt

Fixed refund logic for transaction stuck in NOTIFICATION_REQUESTED or NOTIFICATATION_ERROR statuses.
For those transaction refund has to be performed only if the sendPaymentResult outcome received is KO
This modification are needed in order to not perform refund for transaction expired in NOTIFICATION_REQUESTED or NOTIFICATION_ERROR statuses if the send payment result outcome is OK
Junit tests + local tests with ecommerce local

fix: no refund for trx with send payment result OK

---

pom.xml
src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/NodeService.kt
src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/NodeServiceTests.kt
src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/TestUtil.kt

Depends on https://github.com/pagopa/pagopa-ecommerce-commons/pull/95
👉🏻 **CLOSE PAYMENT OK/KO with authorization completation event** 
Changed the logic to forward the close payment to the node. 
The following fields have been added to the `transactionDetails` object in case of close payment **OK** or **KO** after receiving the request for completion of authorization: 
- brand
- paymentMethodName
- clientId
- errorCode
- timestampOperation
- brokerName
- paymentGateway
- pspOnUs
The field `authorizationCode` will be valorized only in case of close payment **OK** otherwise in case of **KO** the `errorCode` will be valorized.
👉🏻 **CLOSE PAYMENT KO with user cancellation request**
in case of closePayment KO for cancellation by the user will be forwarded only new fields available in the …

feat(close payment) added fields into transactionDetails

---

pom.xml
src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/NodeService.kt
src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/NodeServiceTests.kt

Change transaction details transactionStatus field from "Autorizzato" to "Confermato"
Update constant value in node services
This PR address some bizEvent bounds
Junit tests has been edited and ran

[CHK-1693] update status constants

---

src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/client/NodeClient.kt
src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/exceptions/BadClosePaymentRequest.kt
src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionClosePaymentQueueConsumer.kt
src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/client/NodeClientTest.kt
src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/TransactionClosePaymentQueueConsumerTests.kt

- Remove retry for unrecoverable errors (404 - TransactionNotFound, 400 - Bad request)
- A retry message will not be inserted in the retry queue when this unrecoverable errors are thrown
- Remove useless retries

[CHK-1589] fix closePayment retry logic

---

src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/client/NodeClient.kt
src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/client/NodeClientTest.kt
src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/TestUtil.kt

Fix close payment transaction id parsing as TransactionId domain object 
This modification is needed because event transaction id does not contains dashes and cause unhandled exception in case of 404 Nodo error response
Junit tests

fix(nodo client): transaction id parsing as domain object

---

src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionNotificationsRetryQueueConsumer.kt
src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/common.kt
src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionNotificationsRetryQueueConsumerTest.kt
src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionsRefundEventsConsumerTests.kt

Add logic to write to event dispatcher`dead-letter-queue` for the following cases:
1.  no attempt left for retry sending email to user
2. refund process is interrupted due to an error response for which no more attempts have to be performed, such as an 4xx error or an inconsistent state (for PGS only)
In case there are no attempts left for retry sending an email or perform a refund the retry event have to be written to dead-letter-queue in order to trace this error
Junit tests + local test using eCommerce local

fix: write event to dead letter queue for no left attempt

---

src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionExpirationQueueConsumer.kt
src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/common.kt
src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/DeadLetterTracedQueueAsyncClient.kt
src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionExpirationQueueConsumerTests.kt

- disable refund for expired transaction in authorization completed status
The goal of this PR is to add a check to disable refund for expired transaction in authorization completed event and send event in deadletter.
This step is required waiting async refactoring for `PATH auth-requests`,  currently both the  authorization outcome update and the closepayment are perform in this API, and if it has a response time greater than 10 sec an inconsistent status may occur, i.e. the outcome of the authorization is updated but not the closepayment attempt. So, these cases must be managed in the deadletter.

feat: CHK-224 add refundable manual check for authorization completed transaction

---

src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionExpirationQueueConsumer.kt
src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/common.kt
src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionExpirationQueueConsumer.kt
src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/common.kt
src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionExpirationQueueConsumerTests.kt
src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionExpirationQueueConsumerTests.kt

1. Fix event writing to dead letter queue for transactions stuck in AUTHORIZATION_COMPLETED status.
Logic was written into a filter method and dead letter event writing event was never subscribed.
The fix consisted in change filter to filterWhen method plays a mono that produces a boolean for make filter check
2. Include also transactions stuck in AUTHORIZATION_COMPLETED event that have been expired by transactions-scheduler-service 
3. Ported filter logic to v2 expiration event handler
Those modifications are needed in order to properly write event to dead letter queue in case of refund to be processed manually after a check against Nodo position
Junit tests + local tests using eCommerce local

fix: write event to dead letter queue

---

src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/common.kt
src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/common.kt
src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionsRefundEventsConsumerTests.kt
src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionsRefundEventsConsumerTests.kt

Modified PGS status handling logic for CREATED case: this case should be handled as a non final status and make service perform other refund retry attempts
This modification will cover all that cases when refund call is made just before the authorization process is completed PGS side, reading a CREATED status that will be valid until authorization process is completed.
Skipping those refund retry attempts lead to manual refund to be process for those transactions (eCommerce wants to refund the transaction but cannot succeed (CREATED status received) and did not perform any other attempts.
All those manual refund can be simply avoid making the system perform more attempts when the PGS returned status is CREATED.
Junit tests

fix(refund): [CHK-2264] - perform retries when PGS transaction status is CREATED

---

pom.xml

* mark netty-resolver-dns-native-macos dependency for test only as it causes memleak in prod
The dependency was needed for macOS on ARM arch and was included unconditionally, but it causes a memory leak of non-heap memory in Linux hosts.
Deployment in dev environment and monitoring on memory.

[CHK-2334] fix(deps): mark `netty-resolver-dns-native-macos` dependency for test only as it causes memleak in prod

---

src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionClosePaymentQueueConsumer.kt
src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/ClosePaymentHelper.kt
src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionClosePaymentQueueConsumerTests.kt
src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/ClosePaymentHelperTests.kt

Add cache delete after invoking node close payment for user transaction cancellation flow
This fix restore the payment cache delete logic after the user cancel the transaction

fix: add cache delete after user transaction cancellation close payment

---

src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/common.kt
src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/RefundService.kt
src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionsRefundEventsConsumerTests.kt
src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/RefundServiceTests.kt

Used the correlationId present in the activation event to make the refund  request to NPG.
The change was made to handle with a single correlationId all the transaction of NPG in this PR the logic for the refund  is unified

[CHK-2444] Correlation id into npg refund request

---

src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/ClosePaymentHelper.kt
src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/ClosePaymentHelperTests.kt

- Add missing closure error event in case of transaction to be refund due to close payment KO response (422 HTTP error code with response `Node did not receive RPT yet`
- Remove `refundTransactionPipeline` pipeline call when no retry attempts are left for close payment retry since no refund have to be done in this case
This modification is needed in order to write the closure error event before the refund requested ones. Without closure error event, in fact, transactions event are inconsistent and reduce operation will not perform reduction successfully, discarding refunds events and thinking that transaction is in EXPIRATION status instead of REFUND_REQUESTED/REFUNDED ones
Junit tests + local tests with eCommerce local

fix(v2): missing closure error event in case of refund after close payment

---

src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/common.kt
src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeService.kt
src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/AuhtorizationRequestedHelperTests.kt
src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeServiceTests.kt

* forward NPG `validationServiceId` (for MyBank) if present in NPG `getState`
This PR forwards `validationServiceId` field for MyBank when retrieving an authorization state when NPG didn't notify us.
This field is needed to be forwarded to the later `closePayment` phase.

[CHK-2812] feat(getstate): forward NPG `validationServiceId` if present in NPG `getState`

---

pom.xml
src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/v2/UserReceiptMailBuilder.kt
src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionNotificationsQueueConsumerTest.kt
src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/v2/UserReceiptMailBuilderTest.kt

Depends on https://github.com/pagopa/pagopa-ecommerce-commons/pull/194
Use `companyName` and `description` into success mails `CartTemplate.ItemTemplate` instead of the first value received into send payment result outcome
This modification fix mail request composition for those transactions with a cart of payment notices using the right value for each payment notice as received by Nodo in activate response body
Junit tests

feat: user notification for carts

---

src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/common.kt
src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/AuhtorizationRequestedHelperTests.kt

* forward `errorCode` from NPG when calling `getState`
This PR forwards the `errorCode` field from NPG's `getState` API to eCommerce's `PATCH auth-requests`.
This flow is invoked when NPG doesn't notify us of the payment's outcome so we have to fetch it manually.
Forwarding this field allows us to store it in case of errors during the authorization phase on the payment gateway.

[CHK-2811] feat(getstate): forward `errorCode` from NPG when calling `getState`

---

src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/AuthorizationStateRetrieverService.kt
src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/AuthorizationStateRetrieverServiceTest.kt

* take NPG order id from authorization data when invoking `GET order/:orderId`
Fixes issue when invoking `GET /order/:orderId` with APMs (where `orderId` is not available upon activation but only on authorization request).
This fix is retrocompatible as in case of cards the activation's `orderId` is used as the `authorizationRequestId`.

[CHK-2918] fix: take NPG order id from authorization data when invoking `GET order/:orderId`

---

pom.xml
src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeService.kt
src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeServiceTests.kt

* changed timestamps populated inside `closePayment` `additionalPaymentInformation` like cards, now the populated timestamp is an ISO-8601 local date-time with `Europe/Rome`/`Europe/Paris` timezone
Wrong date-time format broke the  flow after `closePayment`
Updated unit tests + tested with `pagopa-ecommerce-local`
Depends on pagopa/pagopa-infra#2205

[CHK-2976] fix: set `additionalPaymentInformations` timestamps to naive date time format

---

src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeService.kt
src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeServiceTests.kt

Change `additionalPaymentInformations.transactionId` close payment field in order to be valued with the received `bpayEndToEndId` received by NPG
For PSP to correctly reconciliate transaction the `bpayEndToEndId` field have to be used as additionalPaymentInformations.transactionId field into close payment request performed with Bancomat Pay payment method. This field is stored into eCommerce event store as paymentEndToEndId and is then used to populate close payment request
Junit tests

[CHK-3008]-  Bancomat pay close payment

---

src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/common.kt
src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeService.kt
src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/AuhtorizationRequestedHelperTests.kt
src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeServiceTests.kt

Use `bpayEndToEndId` as `paymentEndToEndId` for bancomat pay GET state
For bancomat pay the end to end id to be used for close payment to be used is `bpayEndToEndId`  
Junit tests

feat: [CHK-3007] - use bpayEndToEndId as paymentEndToEndId

---

src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/common.kt
src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeService.kt
src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/utils/EndToEndId.kt
src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/AuhtorizationRequestedHelperTests.kt
src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/services/v2/NodeServiceTests.kt

Update GET state logic for MyBank performed transactions: use `myBankEndToEndId` as paymentEndToEndId field into transactions-service PATCH auth request
This modification is needed in order to properly retrieve payment end to end id for MyBank transactions and use the newly added NPG `myBankEndToEndId` field
Junit tests

[CHK-3011] mybank get state

---

pom.xml
src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/config/OpenTelemetryConfig.kt
src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/ClosePaymentHelper.kt
src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/ClosePaymentHelperTests.kt

Depends on https://github.com/pagopa/pagopa-ecommerce-commons/pull/212
Add tracing for ClosePayment processed requests.
For each performed close payment a span will be add that will trace: pspId, paymentTypeCode, if the transaction is performed with an onboarded or not method, clientId and the Node outcome (OK, KO and eventual error with http and error description)
Those modifications are needed in order to add monitoring to all performed close payments and allow to distinguish close payment operation by client, pspId, Node outcome and so on
Junit tests + test in DEV environment

feat: trace close payment requests

---

src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/client/UserStatsServiceClient.kt
src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/AuthorizationRequestedHelper.kt
src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/AuthorizationRequestedHelperTests.kt

perform POST save usage api call also for those transactions that have reach a state after AUTHORIZATION_REQUESTED status once received event
Authorization requested event is received after a delay after the authorization is performed. 
This mean that the transaction could be in a next status rather then AUTHORIZATION_REQUESTED one once authorization requested event is written in queue.
For those cases only the POST save last usage api call have to be invoked
This modification is required in order to update last usage correctly for all transactions, also the ones that have reach a next status than AUTHORIZATION_REQUESTED one
junit tests

fix: POST save usage for ongoing transactions

---

src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/exceptions/ClosePaymentErrorResponseException.kt
src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v1/TransactionClosePaymentRetryQueueConsumerTests.kt
src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/ClosePaymentHelperTests.kt

Extend automatic refund on Node ClosePayment to properly handle 4xx errors as per https://pagopa.atlassian.net/browse/CHK-3553 specifications
Here an overall on automatic action performed by eCommerce for errors performing Close payment
| http error code                | description                                   | automatic refund | retry |
|--------------------------------|-----------------------------------------------|------------------|-------|
| 400                            | any                                           | ✅                | ❌     |
| 404                            | any                                           | ✅                | ❌     |
| 422                            | `Node did not receive RPT yet`                | ✅                | ❌     |
| 422 …

feat(close payment): add automatic refund for 400 and 404 response codes

---

pom.xml
src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/client/NodeClient.kt
src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/ClosePaymentHelper.kt
src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/eventretry/v2/AuthorizationStateRetrieverRetryService.kt
src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/eventretry/v2/ClosureRetryService.kt
src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/eventretry/v2/NotificationRetryService.kt
src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/eventretry/v2/RefundRetryService.kt
src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/services/eventretry/v2/RetryEventService.kt
src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionNotificationsQueueConsumerTest.kt
src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionNotificationsRetryQueueConsumerTest.kt
src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionRefundRetryQueueConsumerTest.kt
src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/TransactionsRefundEventsConsumerTests.kt
src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/AuthorizationRequestedHelperTests.kt
src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/ClosePaymentHelperTests.kt

Depends on https://github.com/pagopa/pagopa-ecommerce-commons/pull/225
Add tracing for error that occurs performing Node closePayment request.
Those errors will be used to communicate trace and communicate to touchpoint the specific Node error that happened in order to display the correct page to the user
Junit tests + locally using eCommerce local

feat(Node close payment): save error into events

---

src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/ClosePaymentHelper.kt
src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/ClosePaymentHelperTests.kt

Add clear of view "closureErrorData" in case of successful response received by Node during close payment retry
This modification is needed in order to clear "closureErrorData" transaction-view section in the case the close payment retry process is performed successfully in a retry attempt
junit tests

fix: clear closureErrorData in case of response received from Node

---

pom.xml
src/main/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/ClosePaymentHelper.kt
src/test/kotlin/it/pagopa/ecommerce/eventdispatcher/queues/v2/helpers/ClosePaymentHelperTests.kt

Add  info about user canceled request into closed event details
Update the `TransactionClosureData()` constructor
This patch is useful for ecommerce cdc service to make closed event processing indipendent from previous event query

[CHK-4372] Add canceled by user info into close payment data
